[package]
name = "veta-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
veta-core.workspace = true
async-trait.workspace = true
rusqlite.workspace = true
chrono.workspace = true
regex = "1"
